### ISSUE TITLE
Unable to obrtain driver for firefox 

### ISSUE THREAD

**Issue by niranjanakella** [ersinaksar/Dockerized-Firefox-for-Web-Scraping#1]
Hello @ersinaksar, tried the setup described in readme, but encountered the following error:
```
> docker run --rm -e DISPLAY=:99 my-firefox



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py", line 46, in binary_paths
    args = [str(self._get_binary())] + args
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in _get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//test.py", line 24, in <module>
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 57, in __init__
    if finder.get_browser_path():
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

**Comment by niranjanakella** [comment]
@ersinaksar Was able to get it working by changing the config this way 

```
FROM --platform=linux/amd64 python:3.9-slim-buster

# Install Firefox and other dependencies
RUN apt-get update && apt-get install -y firefox-esr xvfb 

# Install Python packages
RUN pip install selenium BeautifulSoup4 lxml

# Install xvfb and xauth packages
RUN apt-get install -y xvfb xauth

# Copy Python script
COPY main.py .

ENV DISPLAY=:99

# Run script with xvfb
CMD ["xvfb-run", "--server-args='-screen 0 1024x768x24'", "--auto-servernum", "python", "main.py"]
```
